Lesson3
MaksimKs/JavaTelegramTasks pull request #1
Opened 2020-08-01 22:01 UTC by MaksimKs

lesson 3 task 1
lesson 3 task 2 (in progress)
lesson 3 task 3

2020-08-02 09:13 UTC, AntonShtabnoy requested changes

2020-08-02 09:13 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task1/TimeInterval.java
> +        this.seconds = inputSeconds;
А если я ввиду 54600 сек - в этом времени содержаться и минуты и часы, а в итоге получится что данные поля класса будут пустыми

2020-08-02 09:13 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task1/TimeInterval.java
> +        if (hours < 0) {
почему hours в методе про minute?

2020-08-02 09:13 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task1/TimeInterval.java
> +        return (this.getSeconds() + (this.getMinutes() * 60) + (this.getHours()* 3600));
внешние скобки лишние

2020-08-02 09:13 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task1/TimeInterval.java
> +    }
static мы еще не проходили - метод должен принимать объект Time и вызываться след. образом time1.equals(time2)

2020-08-02 09:13 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task3/MainFigures.java
> +        интерфеса, но имею разную реализацию методов
Принцип наследования - тут нет, здесь только полиморфизм. Наследование это когда есть какой-то базовый класс, и дочерние которые берут все что есть из базового класса  например имеют свое уникальное поле.

2020-08-03 06:40 UTC, MaksimKs commented
add lesson 3 task 2 (ATM)

2020-08-07 18:51 UTC, AntonShtabnoy approved these changes

2020-08-07 18:51 UTC, AntonShtabnoy commented on src/com/gmail/ksenzhuk_maksim/lesson3/task1/TimeInterval.java
> +        }
я бы в таком случае вообще ничего не сетал, а просто выводил бы сообщение об ошибке

2020-08-07 18:51 UTC, merged